# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.13'

    - name: Build main module
      run: go build -v ./...

    - name: Test main module
      run: go test -v ./...

    - name: Build bbolt eventstore
      run: cd eventstore/bbolt && go build -v ./...

    - name: Test bbolt eventstore
      run: cd eventstore/bbolt && go test -v ./...
        
    - name: Build sql eventstore
      run: cd eventstore/sql && go build -v ./...

    - name: Test sql eventstore
      run: cd eventstore/sql && go test -v ./...
